prune:
  automatic: true
  number: 1
pythonRequirements:
  zip: true
secretsManager: #url do secret manager
vpcId: id da vpc 
vpcConfig:
  securityGroupIds:
    - Ref: SecurityGroup
  subnetIds:
    - #subnets